### PR TITLE
Finnish and Swedish translations updated

### PR DESCRIPTION
**Pull request by msarjakoski**
Updated locales/fi.json and locales/sv.json for latest additions.

### CODE REVIEW

**Comment by juan-g** [comment]
There seems to have been an error. Since there were various recent changes in WorldCasper2, maybe you could pull first from here to your local repository, and then repeat the changes and push again to your GitHub repository. Thank you!

**Comment by msarjakoski** [comment]
Hmm, I seem to trouble understanding how to fix this. I am trying to get my local repo synced, but "git checkout master" gives me "error: pathspec 'master' did not match any file(s) known to git.".  I even recreated the local repo. Should is just totally remove my fork from Github to get a fresh start?

**Comment by juan-g** [comment]
Possibly there was a master/branch confusion. WorldCasper2's master is just Casper, and the base branch for pull requests (optionally with derived branches) should be i18n-translatable-frontend, which appears by default on this repository rather than master.

A fresh start, although not needed, would be of course an easy way (after a backup just in case). But you can first try to pull to your local repository both master and i18n-translatable-frontend branch from this WorldCasper2 repository (upstream), and then force push to your GitHub repository (origin).

**Comment by msarjakoski** [comment]
How does it look like now?

**Comment by juan-g** [comment]
```
<<<<<<< HEAD
...
=======
...
>>>>>>> e5a7775af837a86ae2f62b3f2b5cc3cfe523b801
```
Those are conflicts. They are reported by `git status`, but [resolving conflicts](https://help.github.com/articles/resolving-a-merge-conflict-using-the-command-line/) take quite a lot of care. Not sure if you will prefer to try it or not. Maybe a new fork (upstream -> origin -> local) would be quicker and easier, after making a backup of your translation files at least.

**Comment by msarjakoski** [comment]
Uups, I value your patience. I thought I did resolve all the conflicts. But it seems that while learning I also made a little mess...

**Comment by msarjakoski** [comment]
Manually fixed those conflicts. How about now?

**Comment by juan-g** [comment]
That's OK now for the end result. I've squashed the 39 commits into one, and merged. Thank you!

**Pull request merged**
